# Generated by Django 5.2 on 2025-07-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_alter_like_unique_together_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
