# Generated by Django 5.2 on 2025-08-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_follow_followed_at_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_at',
        ),
    ]
